# Generated by Django 3.2 on 2022-06-09 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhoods', '0002_alter_neighborhood_occupants'),
        ('posts', '0002_auto_20220609_1319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created_at',
            new_name='posted_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_at',
            new_name='posted_at',
        ),
        migrations.AddField(
            model_name='post',
            name='neighbors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='neighborhoods.neighborhood'),
        ),
    ]
