# Generated by Django 3.2 on 2022-06-09 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_comment_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='neighbors',
            new_name='neighbor',
        ),
    ]
