# Generated by Django 3.2 on 2022-06-09 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_rename_body_comment_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='post',
        ),
    ]
