# Generated by Django 3.2 on 2022-06-18 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-posted_at',)},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ('-created_at',)},
        ),
    ]
