# Generated by Django 3.2 on 2022-06-08 20:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('neighborhoods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhood',
            name='occupants',
            field=models.ManyToManyField(blank=True, related_name='occupants', to=settings.AUTH_USER_MODEL),
        ),
    ]
