# Generated by Django 3.2 on 2022-06-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhoods', '0003_alter_neighborhood_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name='neighborhood',
            name='occupants',
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='occupants',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
