# Generated by Django 3.2 on 2022-06-17 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='images/mulyadi-PIlB7BQo5bg-unsplash_lohbh0.jpg', upload_to='images/'),
        ),
    ]
