# Generated by Django 3.2 on 2022-06-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='images/avatar_wqbvxp.svg', upload_to='images/'),
        ),
    ]
